stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'bond_service'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_bond_service'
  POSTGRES_HOST_AUTH_METHOD: trust

precommit:
  stage: lint
  image: ghcr.io/astral-sh/uv:python3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - uv pip install -q pre-commit pre-commit-uv
  script:
    - uv run pre-commit run --show-diff-on-failure --color=always --all-files

pytest:
  stage: test
  image: docker:25.0
  services:
    - docker:dind
  before_script:
    - docker compose -f docker-compose.local.yml build
    - docker compose -f docker-compose.docs.yml build
    - docker compose -f docker-compose.local.yml run --rm django python manage.py migrate
    - docker compose -f docker-compose.local.yml up -d
  script:
    - docker compose -f docker-compose.local.yml run django pytest
