# Generated by Django 5.0.9 on 2025-01-27 07:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bond issuance', max_length=255)),
                ('isin', models.CharField(help_text='ISIN identifier', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, help_text='Bond value', max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Value must be higher than 0')])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Interest rate must be higher than 0')])),
                ('purchase_date', models.DateField(help_text='Date when the bond was purchased')),
                ('maturity_date', models.DateField(help_text='Date when the bond matures')),
                ('payment_frequency', models.PositiveSmallIntegerField(choices=[(1, 'monthly'), (12, 'annually')], default=12, help_text='Frequency of interest payments')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'ordering': ['maturity_date'],
            },
        ),
    ]
